[package]
name = "rust_practice_cards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.4"
egui = "0.21.0"
egui-miniquad = "0.14.0"
macroquad = "0.3.25"
egui-macroquad = "0.15.0"
